version: '3.8'

services:
  app:
    image: online-learning-platform:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: online-learning-platform-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/online_learning
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: online-learning-platform-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: online_learning
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local

